import 'package:flutter/material.dart';

class AppModel {
  final String name, image, description, category;
  final double rating;
  final int review, price;
  List<Color> fcolor;
  List<String> size;
  bool isCheck;

  AppModel({
    required this.name,
    required this.image,
    required this.description,
    required this.category,
    required this.rating,
    required this.review,
    required this.price,
    required this.fcolor,
    required this.size,
    required this.isCheck,
  });
}
List<AppModel> fashionEcommerceApp=[
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
    AppModel(
      name:'t shirt',
      rating:4.9,
      price :295,
      review:136,
      isCheck:true,
      image: 'assets/category/items.png',
      description: '',
      category: 'Women',
      fcolor: [
        Colors.black26,
        Colors.yellow,
        Colors.green,
      ],
      size: [
        'S',
        'M',
        'L',
      ],
    ),
  ];

