// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAob6IZtQqI0zxQxVp6_D1CNSqgC_CsYkE',
    appId: '1:151287417042:web:a3ea150090a7ac94cb850b',
    messagingSenderId: '151287417042',
    projectId: 'e-commerce9-20',
    authDomain: 'e-commerce9-20.firebaseapp.com',
    storageBucket: 'e-commerce9-20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH5RsGUewScND-DRJx6UTblXQSCeIMMEY',
    appId: '1:151287417042:android:cfd5f22d17967f89cb850b',
    messagingSenderId: '151287417042',
    projectId: 'e-commerce9-20',
    storageBucket: 'e-commerce9-20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4TQtiPr3Hy20W7rMTDixt_4fRT_yIqwI',
    appId: '1:151287417042:ios:ae49e2f0a3219497cb850b',
    messagingSenderId: '151287417042',
    projectId: 'e-commerce9-20',
    storageBucket: 'e-commerce9-20.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4TQtiPr3Hy20W7rMTDixt_4fRT_yIqwI',
    appId: '1:151287417042:ios:ae49e2f0a3219497cb850b',
    messagingSenderId: '151287417042',
    projectId: 'e-commerce9-20',
    storageBucket: 'e-commerce9-20.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAob6IZtQqI0zxQxVp6_D1CNSqgC_CsYkE',
    appId: '1:151287417042:web:a9767b231778c27bcb850b',
    messagingSenderId: '151287417042',
    projectId: 'e-commerce9-20',
    authDomain: 'e-commerce9-20.firebaseapp.com',
    storageBucket: 'e-commerce9-20.firebasestorage.app',
  );

}